version: '2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/app
            - ./other:/etc/go-cron
            - nodemodules:/var/www/app/node_modules

volumes:
    nodemodules: {}
